/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dexRouterSol from "./DEXRouter.sol";
export type { dexRouterSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DEXFactory } from "./DEXFactory";
export type { DEXPair } from "./DEXPair";
export type { MockERC20 } from "./MockERC20";
export * as factories from "./factories";
export { DEXFactory__factory } from "./factories/DEXFactory__factory";
export { DEXPair__factory } from "./factories/DEXPair__factory";
export type { DEXRouter } from "./DEXRouter.sol/DEXRouter";
export { DEXRouter__factory } from "./factories/DEXRouter.sol/DEXRouter__factory";
export type { IDEXFactory } from "./DEXRouter.sol/IDEXFactory";
export { IDEXFactory__factory } from "./factories/DEXRouter.sol/IDEXFactory__factory";
export type { IDEXPair } from "./DEXRouter.sol/IDEXPair";
export { IDEXPair__factory } from "./factories/DEXRouter.sol/IDEXPair__factory";
export type { IERC20 } from "./interfaces/IERC20";
export { IERC20__factory } from "./factories/interfaces/IERC20__factory";
export { MockERC20__factory } from "./factories/MockERC20__factory";
